name: dsr-be

services:
  app:
    image: iblcloud/searl-dsr-be:1.0.0
    container_name: searl-dsr-be
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3014:3014"
    volumes:
      - ./logs:/app/logs
